"""Add policies

Revision ID: a68f681a790c
Revises: ab453a5050ff
Create Date: 2026-09-05 13:21:37.161237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68f681a790c'
down_revision: Union[str, Sequence[str], None] = 'ab453a5050ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('max_transaction_amount', sa.Integer(), nullable=True),
    sa.Column('max_contacts', sa.Integer(), nullable=True),
    sa.Column('recovery_window_days', sa.Integer(), nullable=True),
    sa.Column('require_human_approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('policies')
    # ### end Alembic commands ###
